### PR TITLE
Fix #71

### LINKED ISSUE #71: Support NixOS
Comes from <https://github.com/pre-commit/mirrors-clang-format/issues/26>:

> This hook will download .cache/pre-commit/repon0nie2em/py_env-python3.10/lib/python3.10/site-packages/clang_format/data/bin/clang-format for me. However, My OS is NixOS, which doesn't respect HFS so it must patchelf every program. Inspired by ntkme/sass-embedded-host-ruby#116, I NIX_BINTOOLS=/nix/store/ngh5s155lcm1hwsakrfhla536x9g5v4z-binutils-wrapper-2.40 pre-commit run -a. It works for https://github.com/scop/pre-commit-shfmt, but cannot work for this hook. How to make it work?

### PR DESCRIPTION
**Pull request by Freed-Wu**
Refer <https://github.com/pre-commit/mirrors-clang-format/blob/main/.pre-commit-hooks.yaml>

### CODE REVIEW

**Comment by Freed-Wu** [comment]
> you will not install clang-format from a wheel but build it from source

NixOS need to build it from source code (Just only the first time) to make it work. For other users, mirrors-clang-format is enough.

**Comment by dokempf** [comment]
The choice of what pre-commit hook repository to use is not with the end user (who might be a NixOS user) but with the library maintainers. If a library would write this hook into its `.pre-commit-config.yaml` file, it will force a full LLVM from source build onto all users (NixOS or not).

**Comment by dokempf** [comment]
Maybe you should try setting the `PIP_NO_BINARY=:all:` env variable and hope that `pre-commit` passes it through to the actual call to `pip`.

**Comment by Freed-Wu** [comment]
> setting the PIP_NO_BINARY=:all:

:+1:

**Pull request closed without merging**
